coverage:
  precision: 2
  round: down
  range: "5...100"

  status:
    project:
      default:
        enabled: yes
        target: auto
        branch: master
        if_no_uploads: error
        if_ci_failed: error


    patch:
      default:
        enabled: yes
        target: 20%
        if_no_uploads: error


    changes: true

    ignore:
      - gradle/
      - .gitignore
      - .lgtm
      - *.yml
      - *.gradle
      - *.sh
      - gradlew
      - *.bat
      - MAINTAINERS
      - *.md
      - src/libs/
      - src/test/
      - src/main/webapp


  slack:
        default:
          url:
            - https://hooks.slack.com/services/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
          branches:
            - *
          threshold:
            - "0.5%"
          message: "Coverage status: "


comment:
  layout: "header, diff, changes, suggestions"
  behavior: new