coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true

  slack:
        default:
          url:
            - https://hooks.slack.com/services/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
          branches:
            - *
          threshold:
            - "0.5%"
          message: "Coverage status: "


comment:
  layout: "header, diff, changes, suggestions"
  behavior: default